# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    increment_build_number

    # add actions here: https://docs.fastlane.tools/actions
    build_ios_app(
      output_directory: "build",
      output_name: "app.ipa", 
      export_method: "ad-hoc"
    )
  end

  lane :validate_app_center do
    # default release (not mandatory, no notification)
    appcenter_upload(
      owner_name: ENV["OWNER"],
      app_name: ENV["APP_AC"],
      ipa: "./build/app.ipa",
      dsym: "./build/app.app.dSYM.zip",
      group: "Collaborators"
    )

    # mandatory, no notification
    appcenter_upload(
      owner_name: ENV["OWNER"],
      app_name: ENV["APP_AC"],
      ipa: "./build/app.ipa",
      dsym: "./build/app.app.dSYM.zip",
      group: "Collaborators",
      mandatory_update: true,
      notify_testers: false
    )

    # not mandatory, notification, multiple destinations
    appcenter_upload(
      owner_name: ENV["OWNER"],
      app_name: ENV["APP_AC"],
      ipa: "./build/app.ipa",
      dsym: "./build/app.app.dSYM.zip",
      group: "Collaborators,private,public",
      mandatory_update: false,
      notify_testers: true
    )
  end

  lane :validate_hockeyapp do
    # default release (not mandatory, no notification)
    appcenter_upload(
      owner_name: ENV["OWNER"],
      app_name: ENV["APP_HA"],
      ipa: "./build/app.ipa",
      dsym: "./build/app.app.dSYM.zip",
      group: "Collaborators"
    )

    # mandatory, no notification
    appcenter_upload(
      owner_name: ENV["OWNER"],
      app_name: ENV["APP_HA"],
      ipa: "./build/app.ipa",
      dsym: "./build/app.app.dSYM.zip",
      group: "Collaborators",
      mandatory_update: true,
      notify_testers: false
    )

    # not mandatory, notification, multiple destinations
    appcenter_upload(
      owner_name: ENV["OWNER"],
      app_name: ENV["APP_HA"],
      ipa: "./build/app.ipa",
      dsym: "./build/app.app.dSYM.zip",
      group: "Collaborators,sxs-distribution-group,",
      mandatory_update: false,
      notify_testers: true
    )
  end
end
